---
name: Release

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

jobs:
  release-automation:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-release-automation.yml@31ba8dd001caa3008b36ef64ea51d0342d5c0e5a # main
    secrets:
      PROJECT_GITHUB_TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
    with:
      PLUGIN_LIST: "@release-it/conventional-changelog,@release-it/bumper"
